### ISSUE TITLE
RBF pin should be mounted directly onto the EPS board

### ISSUE THREAD

**Issue by vogeldylan** [HeronMkII/pcbs#12]
OBC PCB aligns with an access port in the P-POD. RBF pin should be moved and mounted on the EPS board for convenience and reliability. Should be facing in the same direction as the debugging port.

**Comment by hirolemo** [comment]
RBF PIN now on schematic. Need to practice layout for integrating on the PCB.

**Comment by hirolemo** [comment]
Yes.
