### ISSUE TITLE
OBC EPS V1 001

### ISSUE THREAD

**Issue by jadenreimer** [HeronMkII/pcbs#23]
- [x] Real time clock is troubled. Remove and resolder
- [x] C17 has poor wetting on both sides
- [x] OBC 32M1: pins 17, 18, 19, 29 & 32 have poor wetting
- [x] Top right of ABM3BF7W has poor wetting
- [x] OBC MEM3: pins 1, 2, 3, 6, 7 & 8 seem unconnected with sad heel fillets
- [x] R33: poor left connection to pad
- [x] OBC MEM2: poor heel fillets on pins 1, 2, 7 & 8
- [x] OBC MEM1: pins 1, 2, 3, 4 & 8 have poor heel fillets and pins 1, 3, 4, 6 & 8 have poor wetting
- [x] Overall the wetting and heel fillets of the flash mems are questionable
- [x] U7: poor wetting on pins 8, 12 & 14, missing heel fillets on pins 9, 11 &13
- [x] EPS CAN: poor wetting & fillets on pins 1, 2 & 5
- [x] OBC CAN: poor wetting on pins 1 & 8
- [x] R31 is pulling a wheelie. Really big glob under one side
- [x] C36?(the one in between R35 & R38: pretty spikey
- [x] Overall cleaning of the board is in order

**Comment by alihaydaroglu** [comment]
nice job on the inspection @jadenreimer good luck fixing my mess lol

**Comment by alihaydaroglu** [comment]
adding @jackberezny here so he can do functional testing on it after it's been reworked

**Comment by jadenreimer** [comment]
Soldering should all be fixed, we'll see how it turns out with testing. @jackberezny feel free to call me over tomorrow if something isn't cooperating and we can work it out

**Comment by vogeldylan** [comment]
Assuming this is finished, the issue can be closed.
