### ISSUE TITLE
Switch schematic wrong on bus boards

### ISSUE THREAD

**Issue by alihaydaroglu** [HeronMkII/pcbs#3]
Programmer will work, but nothing will work when connected to UART. (so the reset button won't work)

**Comment by alihaydaroglu** [comment]
@siddMahen i fixed the abuse of github issues

**Comment by vogeldylan** [comment]
![correct_reset_pin](https://user-images.githubusercontent.com/23109037/43339051-3b95eca2-91a6-11e8-95aa-f254004cab29.PNG)

@hirolemo this is what the correct switch layout should look like on OBC-EPS. There should be a way (in the properties panel?) to enable showing the pin numbers on the schematic sheets. Please make this change and upload it.
