### ISSUE TITLE
PAY-Optical PCB iteration

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pcbs#39]
Refer to notes from manufacturing issue: https://github.com/HeronMkII/pcbs/issues/15

**Comment by LornaLan** [comment]
Did some modifications today prior to Payload Functional Testing

- For the filter prior to Instrumentation Amplifier (IA), 50K resistors were switched to 30K to decrease the DC offset of signal (worked quite well)
- Removed all low-pass caps (C28) around IA

- switched the final output resistor array to zero ohms, took off the low-pass caps. The impedance across the circuit is then too small and the output is zero. Need to put the caps back and test.

**Comment by brunofalmeida** [comment]
- Need a faster ADC for better settling time?

**Comment by LornaLan** [comment]
Preperation work for bio-test on Mar 23rd, inspection done Mar 22nd
- A4-1 and A4-7 have incomplete potting filling on the right side with clear opening straight through to the sensor
- A4-2, A4-7, A4-5 LED completely blocked
