### ISSUE TITLE
imu missing from bus PCB

### ISSUE THREAD

**Issue by alihaydaroglu** [HeronMkII/pcbs#4]
it has a weird footprint

**Comment by alihaydaroglu** [comment]
@moha

**Comment by alihaydaroglu** [comment]
@hirolemo

**Comment by alihaydaroglu** [comment]
please ask @Tahreeem for the correct model of the IMU

**Comment by vogeldylan** [comment]
@hirolemo this is something new to add to the schematics

**Comment by vogeldylan** [comment]
Has been added by Mo, superseded by move from OBC to EPS
