### ISSUE TITLE
PAY-SSM PCB iteration

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pcbs#40]
Refer to manufacturing issue: https://github.com/HeronMkII/pcbs/issues/14

**Comment by brunofalmeida** [comment]
Should not have any resistance between CANH and CANL (in the "middle" of the CAN bus), but could add an optional 0 ohm resistor in case we want to change it later.

**Comment by vogeldylan** [comment]
- Issue with the buffer output being connected to the MISO line

**Comment by LornaLan** [comment]
To-dos:
Assume 32 wells.
- [ ] Change 32M1 to 64M1
- [ ] Modify heater control layout: currently assume 5 thermistors per MF chip, average after ADC along heaters
- [ ] Finalize motor control circuit
- [ ] More robust motor position control circuit
- [ ] Organize sensors-digital.SchDoc
