### ISSUE TITLE
Fix microcontroller programming on PAY-SSM

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pcbs#43]
Currently, programming the PAY-Optical microcontroller requires the PAY-SSM switch to be in the RUN position and the SSM_RST button to be pressed.

**Comment by vogeldylan** [comment]
Is this a bug or a nice-to-have? The issue is with the voltage fluctation tolerance of the Pololu programmers. Could be solved by putting slightly larger current limiting resistors in between, but not guaranteed to fix it.

**Comment by brunofalmeida** [comment]
I think it's more of a nice-to-have
