### ISSUE TITLE
Fix numbering of header between PAY-SSM and PAY-Optical

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pcbs#45]
Currently, pin 1 on SSM connects to pin 2 on Optical, pin 2 on SSM connects to pin 1 on Optical, etc. Ideally these should match.

**Comment by vogeldylan** [comment]
This is just how the stackup works, because of the way the connector plugs in. Easy fix in Altium by just mirroring the component along the vertical axis.
