### ISSUE TITLE
Check PAY-Optical PWM output pins

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pcbs#47]
Check if these conflict with any of the SPI/UART lines we need, as well as the PWM registers that it might be conflicting with.

Is there a conflict between SENS_CS and SENS_CLK on the PAY-SSM schematics?

Currently the PAY-SSM PCB -> optical MCU 16-bit timer -> SENS_CLK -> 20-pin header -> PAY-Optical PCB -> SD_CLK_In -> SD CLKIN

**Comment by vogeldylan** [comment]
Issue is now null.
