### ISSUE TITLE
Revisit thermistor/heater numbering and connections

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pcbs#49]
On the PAY-SSM schematics (positioningAndThermistor.SchDoc and heater sheet):
- Might want to use 5 thermistors to control the 5 heaters instead of 3 thermistors to control 5 heaters.
- The thermistors are currently numbered THM1-10. They should be numbered THM0-9 to match the ADC's CH0-9 numbering.
- It appears that the numbering for THM7 and THM8 to CH6 and CH7 is out of order. CH6 and CH7 are flipped in the ordering of the ports for thermistorADC. @vogeldylan I assume this is how the actual PCB is wired? Not a big deal, just need to make a small change in software.

**Comment by XiuLuoShen** [comment]
Which schematic/file is this

**Comment by brunofalmeida** [comment]
On the PAY-SSM board, I forget which file
