### ISSUE TITLE
Decide where flash chips go

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pcbs#50]
Should we have three on OBC? One for each micro? etc.

**Comment by vogeldylan** [comment]
@brunofalmeida what was the outcome of this decision? No flash on PAY & EPS?

**Comment by brunofalmeida** [comment]
I realize we forgot to discuss this at the meeting, but I recommend 3 flash on OBC, non on PAY & EPS. @alihaydaroglu thoughts?
