### ISSUE TITLE
EPS Converter Testing Manufacturing

### ISSUE THREAD

**Issue by jadenreimer** [HeronMkII/pcbs#51]
Boost:
- [ ] converter: pins 3&4, 5&6, 7&8, 12&13, 14&15 are shorted together (unsure of how many of these are intentional). Pin 7-8 has unflowed solder paste
- [ ] R1 has too much solder (cold joint)
- [ ] 0 ohm Rsense is very sketchy (bottom right)
- [ ] Cbst has unsoldered paste
- [ ] Left side of the inductor (L) is poorly connected
- [ ] Rlim has unflowed solder paste on the top
- [ ] Connection on C41 on the right looks like it needs more solder

Buck-boost:
- [ ] R1 and R2 not electrically connected
- [x] Rfbb is missing 
- [x] connection of converter pins and pads needs to be checked with a multimeter

**Comment by vogeldylan** [comment]
@jadenreimer any updates on this issue?
