### ISSUE TITLE
RTC Battery Size Constraints

### ISSUE THREAD

**Issue by jadenreimer** [HeronMkII/pcbs#52]
- Need to identify a battery of ~3 Ah that is short enough to fit on either the OBC or EPS boards so the RTC can operate for the ~8 months after we hand the satellite over to Spaceflight.
- Is it possible to link multiple batteries together for the 3Ah?
- Could the batteries fit anywhere on the board so long as it doesn't intrude on other critical components?

Mechanical drawings of EPS and OBC, for reference:
[OBC Drawing v1.pdf](https://github.com/HeronMkII/pcbs/files/2408045/OBC.Drawing.v1.pdf)
[EPS Drawing v1.pdf](https://github.com/HeronMkII/pcbs/files/2408047/EPS.Drawing.v1.pdf)

**Comment by vogeldylan** [comment]
Should re-spec this to just turn on after RBF or deployment switches are pulled. I.e. we would have to set the initial time in orbit, but it would safeguard against power failure.
