### ISSUE TITLE
Fix PAY-SSM heater comparator circuit

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pcbs#57]
The IN+ and IN- inputs are currently flipped. Currently the thermistor goes to IN+ while the DAC goes to IN-, but the DAC should go to IN+ while the thermistor goes to IN-.

Edit: Apparently it was designed using a non-inverting comparator but should use an inverting comparator.

**Comment by vogeldylan** [comment]
Will order new, inverting comparators to fix the current prototype.

**Comment by vogeldylan** [comment]
The [TS391ILT](https://www.digikey.ca/short/pcdzc8) comparator was ordered and soldered onto the existing PAY-SSM prototype. Schematic in pcbs-common has been updated to reflect the corrected wiring.
