### ISSUE TITLE
Decide on IMU positioning

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pcbs#61]
From what was brought up at the design review, we have 3 options if we want the IMU to be located more towards the centre of the satellite:
1. Move the OBC PCB to be mounted at the centre of the EPS PCB
2. Put the IMU on the EPS PCB and route its SPI lines through the butterfly connector to the OBC PCB
3. Put the IMU on the PAY-SSM PCB

**Comment by vogeldylan** [comment]
IMU position has been reflected in the system control drawings
