### ISSUE TITLE
Add headers for option of shorting UART pins

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pcbs#63]
As suggested by @vogeldylan, for launch we should be able to short the different programming/debugging/transceiver UART lines together, just in case vibe changes the switch positions. For testing, we will place a jumper to short the pins, but we will eventually solder the pins together before launch.

Need to add:
1) A 2-pin male header connecting programming/debugging TX to transceiver RxD
2) A 2-pin male header connecting programming/debugging RX to transceiver TxD

**Comment by vogeldylan** [comment]
See also #58. Header position has been added to system control drawings.
