### ISSUE TITLE
PCB colours

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pcbs#66]
The solar panel PCBs need to be coloured white for thermal requirements. Check with structures/thermal to confirm.

**Comment by jadenreimer** [comment]
colours
![aussieparrot](https://cultofthepartyparrot.com/parrots/aussieparrot.gif)

**Comment by hirolemo** [comment]
Ah yes colours. The true dilema

**Comment by vogeldylan** [comment]
Why

**Comment by vogeldylan** [comment]
As per Eric on 2018-21-31, thermal has no requirements on colour and we can choose our favorite one.

**Comment by brunofalmeida** [comment]
@vogeldylan not even for solar PCBs?
