### ISSUE TITLE
Fix LDO on PAY-Optical

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pcbs#68]
Use the proper LDO and footprint on PAY-Optical.

**Comment by vogeldylan** [comment]
The [TPS73430DRVT](https://www.digikey.ca/short/pcdp0v) LDO was selected by Andrew and soldered onto the existing prototype of PAY-Optical. Not the one that was designed onto the board, but seems to be working nominally.

For the future, the enable pin of the LDO needs to be changed in the schematics.
