### ISSUE TITLE
EPS Board Manufacturing

### ISSUE THREAD

**Issue by vogeldylan** [HeronMkII/pcbs#69]
Missing passives:
- C6
- C35
- C38

- still need to place ICs

**Comment by brunofalmeida** [comment]
- [ ] Check the resistors/caps below C40, the middle 2 capacitors might be shorted (or just have excess flux that should be cleaned)
- [ ] C38 is messed
- [ ] Excess flux on U15
- [ ] What's going on with L1?
- [ ] UART header in bottom centre is crooked - is it a big deal?
- [ ] U2 is crooked
- [ ] Huge blob of flux in the area near U2

**Comment by brunofalmeida** [comment]
- [ ] DSUB header pin layout is wrong

**Comment by brunofalmeida** [comment]
- [ ] ADC's SDO pin (pin 26 to MISO) waveform looks weird
