### ISSUE TITLE
one of the first iteration obc boards doesn't work

### ISSUE THREAD

**Issue by alihaydaroglu** [HeronMkII/pcbs#7]
>Its OBC 001, or something like that. The issue occurs sporadically; I had it working for 4 days in a row >without issue, only to have it fail later in the lab. I believe the SCK pin is open/disconnected from the >MCU, but I'm not sure.

**Comment by vogeldylan** [comment]
Should this board be fixed or discarded?

**Comment by vogeldylan** [comment]
No updates on this
