### ISSUE TITLE
System PCB v2 Manufacturing

### ISSUE THREAD

**Issue by LornaLan** [HeronMkII/pcbs#70]
Current System debugging PCB (v2) issue:
- footprint of non-inverting buffer SN74LV07A is not correct; should be PW instead of D
- more bugs will be posted here if any more occured

**Comment by brunofalmeida** [comment]
- [ ] DSUB pin layout is wrong

**Comment by vogeldylan** [comment]
RST buttons on the systems board were wired incorrectly. The pins that were used to connect the RST line are always shorted together. Button connects that pair to the opposite pair.

Fixed it by cutting the leg off one side of the button, and soldering a wire from the other pair to the exposed pad. Systems can now RST connected boards.
