### ISSUE TITLE
OBC v2 Manufacturing

### ISSUE THREAD

**Issue by vogeldylan** [HeronMkII/pcbs#71]
Initial issue creation

- [ ] Missing SPI-I2C bridge IC

**Comment by brunofalmeida** [comment]
@hirolemo 's inspection report:
- [ ] U3 - pins 7-8, 11-13, 17-19, 31-32 shorted
- [ ] S2 - bottom left pin floating
- [ ] R6 - solder mount

**Comment by brunofalmeida** [comment]
My fixes:
- [ ] R15 (R40 in schematic export) - comment says 30k, but value says 10 - for lowpass filter, 10 is the correct value but 0 is also OK

**Comment by brunofalmeida** [comment]
Started testing software:
- Uploaded a program successfully (after patching `avrdude.conf` to support the 64M1 and adjusting the makefile)
- UART TX and RX working (`uart_print` and `uart_echo` programs)
- Programming switch and RST button working

**Comment by vogeldylan** [comment]
@brunofalmeida can you change notes to use the bullet point, rather than checkbox? Were the solder issues you mentioned fixed?

**Comment by brunofalmeida** [comment]
@vogeldylan Yeah makes sense. All the soldering issues we were aware of were fixed.

**Comment by brunofalmeida** [comment]
Changed I2C from 3.3V to 5V:
- Soldered U6 (level translator IC), R3 (replaced with 220k), R16/R23 (replaced with 5.1k)
- Desoldered R21/R22

For OBC on its own (not connected to anything), 5V I2C seems to be working (oscilloscope probing shows SCL and SDA are at 5V)

**Comment by brunofalmeida** [comment]
Tested I2C with 5V level translator, all seems to be working

**Comment by brunofalmeida** [comment]
Changed I2C back to 3V3 configuration:
- Desoldered U6, C3, R3, R16, R23
- Left R7, R8 on (pullups to 3V3)
- Soldered R21, R22
