### ISSUE TITLE
EPS PCB Debugging

### ISSUE THREAD

**Issue by jadenreimer** [HeronMkII/pcbs#76]
Items to fix on the PCB:
- Converter performance optimization
- Battery protection circuit: kills the board on startup
- diodes have a weird behaviour coming from the solar panel side of things
- Deployment switches need a redesign for current paths
- one of the heater LEDs will turn on when it shouldn't

Comments from Sam:
Converters:
If they work but aren't regulating properly it's likely something to do with the feedback
Recommendation: try a bunch of different loading conditions and try to show the gating signals or inductor current on the scope.
That should give you an idea of what the controller is doing. If it's analog control, the chip may also have a feedback pin and measuring the voltage on that usually gives insight. Compare the measured value to the datasheet range.
Generally if the value is too close to the datasheet bounds your controller is going to have trouble regulating.

Protection circuit:
For the battery protection if the problem is when the  protection triggers, double check any feedback resistors and consider changing them to +/-0.1% ones.
Guess on what is up with the protection circuit is that there is some start up trick in the IC itself, and that if you read the data sheet carefully you'll find some pin connection or RC circuit timer thing that might solve this problem.
Technically there should be some sort of wakeup sequence for the IC so that it knows what to do when it first gets power.

Roberto's comments:
- check the ESR drop of our capacitors, especially the 47uF capacitors
- consider implementing a charger IC, eg. LT3652

**Comment by brunofalmeida** [comment]
- ADC channel 5 (-X solar panel current) always reads around 3.3A (corresponds to ADC channel voltage of 3.3V)
- Need to test shunting based on battery voltage
