### ISSUE TITLE
SYS PCB flight model improvements

### ISSUE THREAD

**Issue by brunofalmeida** [HeronMkII/pcbs#77]
- [x] Fix reset button connections (ask @vogeldylan) - refer to greenwiring on current PCB

**Comment by LornaLan** [comment]
- *make sure EPS mini D-sub and SYS D-sub are aligned.*
- Fix EPS programming header

**Comment by LornaLan** [comment]
EPS programming header's issue fixed (on EPS).

**Comment by LornaLan** [comment]
- [ ] Fix the D-sub header to agree with the system wiring diagram
- [ ] Fix reset button connections
- [ ] Fix panel +/- label

**Comment by brunofalmeida** [comment]
Look into issues with LEDs turning on and flickering on/off randomly (from BUS integration test on 2019-06-15)
- Stray charges?
- Pullup/pulldown resistors?
- More capacitors?

**Comment by brunofalmeida** [comment]
- [ ] See notes from #70

**Comment by brunofalmeida** [comment]
Need to fix battery connector - which footprint are we using?

**Comment by LornaLan** [comment]
Used a screw terminal for battery connector, should be good
