### ISSUE TITLE
PAY LED PCB Flight Model Improvements

### ISSUE THREAD

**Issue by vogeldylan** [HeronMkII/pcbs#78]
* Make the diode designation clearer, i.e. ensure it's clear which diode goes to which channel

**Comment by LornaLan** [comment]
Notes to myself: label the LEDs according to pay-optical setup. Have a better channel-LED scheme for MCP23S17 pex on board.

**Comment by LornaLan** [comment]
- [ Re-assign numbers to LEDs & PEX for better readability ]
- [ Re-consider LED header position]

**Comment by vogeldylan** [comment]
Redo entire board to match new control architecture.

**Comment by brunofalmeida** [comment]
- Check LED footprint orientation (#18)
