### ISSUE TITLE
pcbs-common Improvements

### ISSUE THREAD

**Issue by jadenreimer** [HeronMkII/pcbs#84]
- [ ] add a silkscreen notch for programming header orientation to footprint (does this matter with the change in programming header selection?)
- [x] programming header pin arrangement seems to be flipped (referencing from EPS V2) and has no square pin 1 marker
- [x] similarly, run-mode 4-pin header has no square pin 1 marker
- [x] heater control comparator output net name disconnected from net
- [ ] differential pair labels should be added to the CAN schematic for CANH and CANL
- [x] add 10uF to the PEX

**Comment by brunofalmeida** [comment]
@vogeldylan In adc-circuit sheet, should VREF_2V5 be labelled as a power net instead of a signal net? It would clarify net naming if power nets take priority

**Comment by vogeldylan** [comment]
@brunofalmeida can you give a use case where having 2V5 as a signal caused net naming issues? The signal isn't really meant to be used as a power rail (10 mA max, serves as the reference for the ADC so susceptible to noise)

**Comment by brunofalmeida** [comment]
See ADC on current PAY-SSM design

**Comment by vogeldylan** [comment]
I see your point but raise you the following 
![image](https://user-images.githubusercontent.com/23109037/63071281-addcd180-beec-11e9-9659-031516e43dac.png)

**Comment by vogeldylan** [comment]
(i.e. this shouldn't be an issue with this design, not sure why it is, not going to change the schematic in pcbs-common)

**Comment by vogeldylan** [comment]
- Silkscreen notch should be added by the designer, since it isn't associated with the part itself
- CAN in our design doesn't require differential length matching

**Comment by brunofalmeida** [comment]
@LornaLan I guess you need to tie the VCC2V5 output of the subsheet to a power net
