### ISSUE TITLE
programming headers on systems debug board have incorrect layout

### ISSUE THREAD

**Issue by alihaydaroglu** [HeronMkII/pcbs#9]
@LornaLan please note for next iteration. Very nicely done otherwise though! i'm planning on getting it to work today, will send you pics when i do

**Comment by vogeldylan** [comment]
![programming-mode](https://user-images.githubusercontent.com/23109037/41827829-a5fc55f6-77ff-11e8-98b4-0035086adaf7.png)

**Comment by vogeldylan** [comment]
![prog-header-ref](https://user-images.githubusercontent.com/23109037/41827844-bc93e7e8-77ff-11e8-9442-d434167a7b0c.png)

**Comment by LornaLan** [comment]
Got it. Will layout the PCB soon
